const CARDS = { #Value, suit, type 0 = number card, 1 = face card
	#clubs
	"ace_of_clubs" : [1, "club", 0],
	"2_of_clubs" : [2, "club", 0],
	"3_of_clubs" : [3, "club", 0],
	"4_of_clubs" : [4, "club", 0],
	"5_of_clubs" : [5, "club", 0],
	"6_of_clubs" : [6, "club", 0],
	"7_of_clubs" : [7, "club", 0],
	"8_of_clubs" : [8, "club", 0],
	"9_of_clubs" : [9, "club", 0],
	"10_of_clubs" : [10, "club", 0],
	"jack_of_clubs" : [0, "club", 1],
	"queen_of_clubs" : [0, "club", 1],
	"king_of_clubs" : [0, "club", 1],
	#diamonds
	"ace_of_diamonds" : [1, "diamond", 0],
	"2_of_diamonds" : [2, "diamond", 0],
	"3_of_diamonds" : [3, "diamond", 0],
	"4_of_diamonds" : [4, "diamond", 0],
	"5_of_diamonds" : [5, "diamond", 0],
	"6_of_diamonds" : [6, "diamond", 0],
	"7_of_diamonds" : [7, "diamond", 0],
	"8_of_diamonds" : [8, "diamond", 0],
	"9_of_diamonds" : [9, "diamond", 0],
	"10_of_diamonds" : [10, "diamond", 0],
	"jack_of_diamonds" : [0, "diamond", 1],
	"queen_of_diamonds" : [0, "diamond", 1],
	"king_of_diamonds" : [0, "diamond", 1],
	#hearts
	"ace_of_hearts" : [1, "heart", 0],
	"2_of_hearts" : [2, "heart", 0],
	"3_of_hearts" : [3, "heart", 0],
	"4_of_hearts" : [4, "heart", 0],
	"5_of_hearts" : [5, "heart", 0],
	"6_of_hearts" : [6, "heart", 0],
	"7_of_hearts" : [7, "heart", 0],
	"8_of_hearts" : [8, "heart", 0],
	"9_of_hearts" : [9, "heart", 0],
	"10_of_hearts" : [10, "heart", 0],
	"jack_of_hearts" : [0, "heart", 1],
	"queen_of_hearts" : [0, "heart", 1],
	"king_of_hearts" : [0, "heart", 1],
	#spades
	"ace_of_spades" : [1, "spade", 0],
	"2_of_spades" : [2, "spade", 0],
	"3_of_spades" : [3, "spade", 0],
	"4_of_spades" : [4, "spade", 0],
	"5_of_spades" : [5, "spade", 0],
	"6_of_spades" : [6, "spade", 0],
	"7_of_spades" : [7, "spade", 0],
	"8_of_spades" : [8, "spade", 0],
	"9_of_spades" : [9, "spade", 0],
	"10_of_spades" : [10, "spade", 0],
	"jack_of_spades" : [0, "spade", 1],
	"queen_of_spades" : [0, "spade", 1],
	"king_of_spades" : [0, "spade", 1],
	#joker
	"joker" : [0, "none", 1],
}
