const CARDS = { #Value, suit, number/face card, rank
	#clubs
	"ace_of_clubs" : [1, "clubs", "number card"], #0
	"2_of_clubs" : [2, "clubs", "number card"],
	"3_of_clubs" : [3, "clubs", "number card"],
	"4_of_clubs" : [4, "clubs", "number card"],
	"5_of_clubs" : [5, "clubs", "number card"],
	"6_of_clubs" : [6, "clubs", "number card"],
	"7_of_clubs" : [7, "clubs", "number card"],
	"8_of_clubs" : [8, "clubs", "number card"],
	"9_of_clubs" : [9, "clubs", "number card"],
	"10_of_clubs" : [10, "clubs", "number card"],
	"jack_of_clubs" : [0, "clubs", "jack"],
	"queen_of_clubs" : [0, "clubs", "queen"],
	"king_of_clubs" : [0, "clubs", "king"], #12
	#diamonds
	"ace_of_diamonds" : [1, "diamonds", "number card"],
	"2_of_diamonds" : [2, "diamonds", "number card"],
	"3_of_diamonds" : [3, "diamonds", "number card"],
	"4_of_diamonds" : [4, "diamonds", "number card"],
	"5_of_diamonds" : [5, "diamonds", "number card"],
	"6_of_diamonds" : [6, "diamonds", "number card"],
	"7_of_diamonds" : [7, "diamonds", "number card"],
	"8_of_diamonds" : [8, "diamonds", "number card"],
	"9_of_diamonds" : [9, "diamonds", "number card"],
	"10_of_diamonds" : [10, "diamonds", "number card"],
	"jack_of_diamonds" : [0, "diamonds", "jack"],
	"queen_of_diamonds" : [0, "diamonds", "queen"],
	"king_of_diamonds" : [0, "diamonds", "king"],
	#hearts
	"ace_of_hearts" : [1, "hearts", "number card"],
	"2_of_hearts" : [2, "hearts", "number card"],
	"3_of_hearts" : [3, "hearts", "number card"],
	"4_of_hearts" : [4, "hearts", "number card"],
	"5_of_hearts" : [5, "hearts", "number card"],
	"6_of_hearts" : [6, "hearts", "number card"],
	"7_of_hearts" : [7, "hearts", "number card"],
	"8_of_hearts" : [8, "hearts", "number card"],
	"9_of_hearts" : [9, "hearts", "number card"],
	"10_of_hearts" : [10, "hearts", "number card"],
	"jack_of_hearts" : [0, "hearts", "jack"],
	"queen_of_hearts" : [0, "hearts", "queen"],
	"king_of_hearts" : [0, "hearts", "king"],
	#spades
	"ace_of_spades" : [1, "spades", "number card"],
	"2_of_spades" : [2, "spades", "number card"],
	"3_of_spades" : [3, "spades", "number card"],
	"4_of_spades" : [4, "spades", "number card"],
	"5_of_spades" : [5, "spades", "number card"],
	"6_of_spades" : [6, "spades", "number card"],
	"7_of_spades" : [7, "spades", "number card"],
	"8_of_spades" : [8, "spades", "number card"],
	"9_of_spades" : [9, "spades", "number card"],
	"10_of_spades" : [10, "spades", "number card"],
	"jack_of_spades" : [0, "spades", "jack"],
	"queen_of_spades" : [0, "spades", "queen"],
	"king_of_spades" : [0, "spades", "king"],
	#joker
	"joker" : [0, "none", "joker"],
}
